// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// DummyServiceClient is the client API for DummyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DummyServiceClient interface {
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
}

type dummyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDummyServiceClient(cc grpc.ClientConnInterface) DummyServiceClient {
	return &dummyServiceClient{cc}
}

var dummyServiceListAccountsStreamDesc = &grpc.StreamDesc{
	StreamName: "ListAccounts",
}

func (c *dummyServiceClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/v2.mod_services.DummyService/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DummyServiceService is the service API for DummyService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterDummyServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type DummyServiceService struct {
	ListAccounts func(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
}

func (s *DummyServiceService) listAccounts(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	if s.ListAccounts == nil {
		return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
	}
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/v2.mod_services.DummyService/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterDummyServiceService registers a service implementation with a gRPC server.
func RegisterDummyServiceService(s grpc.ServiceRegistrar, srv *DummyServiceService) {
	sd := grpc.ServiceDesc{
		ServiceName: "v2.mod_services.DummyService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "ListAccounts",
				Handler:    srv.listAccounts,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "services.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewDummyServiceService creates a new DummyServiceService containing the
// implemented methods of the DummyService service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewDummyServiceService(s interface{}) *DummyServiceService {
	ns := &DummyServiceService{}
	if h, ok := s.(interface {
		ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	}); ok {
		ns.ListAccounts = h.ListAccounts
	}
	return ns
}

// UnstableDummyServiceService is the service API for DummyService service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableDummyServiceService interface {
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
}
