// Code generated by protoc-gen-cobra. DO NOT EDIT.

package v2

import (
	client "github.com/getcouragenow/protoc-gen-cobra/client"
	flag "github.com/getcouragenow/protoc-gen-cobra/flag"
	iocodec "github.com/getcouragenow/protoc-gen-cobra/iocodec"
	cobra "github.com/spf13/cobra"
	grpc "google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
)

func SurveyServiceClientCommand(options ...client.Option) *cobra.Command {
	cfg := client.NewConfig(options...)
	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("SurveyService"),
		Short: "SurveyService service client",
		Long:  "",
	}
	cfg.BindFlags(cmd.PersistentFlags())
	cmd.AddCommand(
		_SurveyServiceNewSurveyProjectCommand(cfg),
		_SurveyServiceGetSurveyProjectCommand(cfg),
		_SurveyServiceListSurveyProjectCommand(cfg),
		_SurveyServiceUpdateSurveyProjectCommand(cfg),
		_SurveyServiceDeleteSurveyProjectCommand(cfg),
		_SurveyServiceNewSurveyUserCommand(cfg),
		_SurveyServiceGetSurveyUserCommand(cfg),
		_SurveyServiceListSurveyUserCommand(cfg),
		_SurveyServiceUpdateSurveyUserCommand(cfg),
		_SurveyServiceDeleteSurveyUserCommand(cfg),
	)
	return cmd
}

func _SurveyServiceNewSurveyProjectCommand(cfg *client.Config) *cobra.Command {
	req := &NewSurveyProjectRequest{}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("NewSurveyProject"),
		Short: "NewSurveyProject RPC client",
		Long:  "Projects",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService", "NewSurveyProject"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewSurveyServiceClient(cc)
				v := &NewSurveyProjectRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.NewSurveyProject(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.SysAccountProjectId, cfg.FlagNamer("SysAccountProjectId"), "", "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.SurveySchemaTypes, cfg.FlagNamer("SurveySchemaTypes"), "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.SurveyFilterTypes, cfg.FlagNamer("SurveyFilterTypes"), "")

	return cmd
}

func _SurveyServiceGetSurveyProjectCommand(cfg *client.Config) *cobra.Command {
	req := &IdRequest{}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("GetSurveyProject"),
		Short: "GetSurveyProject RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService", "GetSurveyProject"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewSurveyServiceClient(cc)
				v := &IdRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.GetSurveyProject(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.SurveyUserId, cfg.FlagNamer("SurveyUserId"), "", "")
	cmd.PersistentFlags().StringVar(&req.SysAccountId, cfg.FlagNamer("SysAccountId"), "", "")
	cmd.PersistentFlags().StringVar(&req.SurveyProjectId, cfg.FlagNamer("SurveyProjectId"), "", "")

	return cmd
}

func _SurveyServiceListSurveyProjectCommand(cfg *client.Config) *cobra.Command {
	req := &ListRequest{
		IdRequest: &IdRequest{},
	}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("ListSurveyProject"),
		Short: "ListSurveyProject RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService", "ListSurveyProject"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewSurveyServiceClient(cc)
				v := &ListRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.ListSurveyProject(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.IdRequest.SurveyUserId, cfg.FlagNamer("IdRequest SurveyUserId"), "", "")
	cmd.PersistentFlags().StringVar(&req.IdRequest.SysAccountId, cfg.FlagNamer("IdRequest SysAccountId"), "", "")
	cmd.PersistentFlags().StringVar(&req.IdRequest.SurveyProjectId, cfg.FlagNamer("IdRequest SurveyProjectId"), "", "")
	cmd.PersistentFlags().Int64Var(&req.PerPageEntries, cfg.FlagNamer("PerPageEntries"), 0, "")
	cmd.PersistentFlags().StringVar(&req.OrderBy, cfg.FlagNamer("OrderBy"), "", "")
	cmd.PersistentFlags().StringVar(&req.CurrentPageId, cfg.FlagNamer("CurrentPageId"), "", "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.Filters, cfg.FlagNamer("Filters"), "")

	return cmd
}

func _SurveyServiceUpdateSurveyProjectCommand(cfg *client.Config) *cobra.Command {
	req := &UpdateSurveyProjectRequest{}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("UpdateSurveyProject"),
		Short: "UpdateSurveyProject RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService", "UpdateSurveyProject"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewSurveyServiceClient(cc)
				v := &UpdateSurveyProjectRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.UpdateSurveyProject(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.SurveyProjectId, cfg.FlagNamer("SurveyProjectId"), "", "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.SurveySchemaTypes, cfg.FlagNamer("SurveySchemaTypes"), "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.SurveyFilterTypes, cfg.FlagNamer("SurveyFilterTypes"), "")

	return cmd
}

func _SurveyServiceDeleteSurveyProjectCommand(cfg *client.Config) *cobra.Command {
	req := &IdRequest{}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("DeleteSurveyProject"),
		Short: "DeleteSurveyProject RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService", "DeleteSurveyProject"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewSurveyServiceClient(cc)
				v := &IdRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.DeleteSurveyProject(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.SurveyUserId, cfg.FlagNamer("SurveyUserId"), "", "")
	cmd.PersistentFlags().StringVar(&req.SysAccountId, cfg.FlagNamer("SysAccountId"), "", "")
	cmd.PersistentFlags().StringVar(&req.SurveyProjectId, cfg.FlagNamer("SurveyProjectId"), "", "")

	return cmd
}

func _SurveyServiceNewSurveyUserCommand(cfg *client.Config) *cobra.Command {
	req := &NewSurveyUserRequest{}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("NewSurveyUser"),
		Short: "NewSurveyUser RPC client",
		Long:  "Users",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService", "NewSurveyUser"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewSurveyServiceClient(cc)
				v := &NewSurveyUserRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.NewSurveyUser(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.SurveyProjectId, cfg.FlagNamer("SurveyProjectId"), "", "")
	cmd.PersistentFlags().StringVar(&req.SysAccountUserId, cfg.FlagNamer("SysAccountUserId"), "", "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.SurveySchemaTypes, cfg.FlagNamer("SurveySchemaTypes"), "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.SurveyFilterTypes, cfg.FlagNamer("SurveyFilterTypes"), "")

	return cmd
}

func _SurveyServiceGetSurveyUserCommand(cfg *client.Config) *cobra.Command {
	req := &IdRequest{}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("GetSurveyUser"),
		Short: "GetSurveyUser RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService", "GetSurveyUser"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewSurveyServiceClient(cc)
				v := &IdRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.GetSurveyUser(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.SurveyUserId, cfg.FlagNamer("SurveyUserId"), "", "")
	cmd.PersistentFlags().StringVar(&req.SysAccountId, cfg.FlagNamer("SysAccountId"), "", "")
	cmd.PersistentFlags().StringVar(&req.SurveyProjectId, cfg.FlagNamer("SurveyProjectId"), "", "")

	return cmd
}

func _SurveyServiceListSurveyUserCommand(cfg *client.Config) *cobra.Command {
	req := &ListRequest{
		IdRequest: &IdRequest{},
	}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("ListSurveyUser"),
		Short: "ListSurveyUser RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService", "ListSurveyUser"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewSurveyServiceClient(cc)
				v := &ListRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.ListSurveyUser(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.IdRequest.SurveyUserId, cfg.FlagNamer("IdRequest SurveyUserId"), "", "")
	cmd.PersistentFlags().StringVar(&req.IdRequest.SysAccountId, cfg.FlagNamer("IdRequest SysAccountId"), "", "")
	cmd.PersistentFlags().StringVar(&req.IdRequest.SurveyProjectId, cfg.FlagNamer("IdRequest SurveyProjectId"), "", "")
	cmd.PersistentFlags().Int64Var(&req.PerPageEntries, cfg.FlagNamer("PerPageEntries"), 0, "")
	cmd.PersistentFlags().StringVar(&req.OrderBy, cfg.FlagNamer("OrderBy"), "", "")
	cmd.PersistentFlags().StringVar(&req.CurrentPageId, cfg.FlagNamer("CurrentPageId"), "", "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.Filters, cfg.FlagNamer("Filters"), "")

	return cmd
}

func _SurveyServiceUpdateSurveyUserCommand(cfg *client.Config) *cobra.Command {
	req := &UpdateSurveyUserRequest{}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("UpdateSurveyUser"),
		Short: "UpdateSurveyUser RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService", "UpdateSurveyUser"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewSurveyServiceClient(cc)
				v := &UpdateSurveyUserRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.UpdateSurveyUser(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.SurveyUserId, cfg.FlagNamer("SurveyUserId"), "", "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.SurveySchemaTypes, cfg.FlagNamer("SurveySchemaTypes"), "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.SurveyFilterTypes, cfg.FlagNamer("SurveyFilterTypes"), "")

	return cmd
}

func _SurveyServiceDeleteSurveyUserCommand(cfg *client.Config) *cobra.Command {
	req := &IdRequest{}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("DeleteSurveyUser"),
		Short: "DeleteSurveyUser RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "SurveyService", "DeleteSurveyUser"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewSurveyServiceClient(cc)
				v := &IdRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.DeleteSurveyUser(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.SurveyUserId, cfg.FlagNamer("SurveyUserId"), "", "")
	cmd.PersistentFlags().StringVar(&req.SysAccountId, cfg.FlagNamer("SysAccountId"), "", "")
	cmd.PersistentFlags().StringVar(&req.SurveyProjectId, cfg.FlagNamer("SurveyProjectId"), "", "")

	return cmd
}
